enum LoadingSteps {
  MARS_FRAMEWORK_ADDED = "MARS_FRAMEWORK_ADDED",
  MONACO_SERVICES_INSTALLED = "MONACO_SERVICES_INSTALLED",
  LANGUAGE_CLIENT_STARTED = "LANGUAGE_CLIENT_STARTED",
  LANGUAGE_SERVER_INITIALIZED = "LANGUAGE_SERVER_INITIALIZED",
  MODELS_READ = "MODELS_READ",
}

export default LoadingSteps;
