enum LoadingSteps {
  MARS_FRAMEWORK_ADDED = "MARS_FRAMEWORK_ADDED",
  MONACO_SERVICES_INSTALLED = "MONACO_SERVICES_INSTALLED",
  MODELS_READ = "MODELS_READ",
  LANGUAGE_CLIENT_STARTED = "LANGUAGE_CLIENT_STARTED",
  LANGUAGE_SERVER_INITIALIZED = "LANGUAGE_SERVER_INITIALIZED",
  PROJECT_INITIALIZED = "PROJECT_INITIALIZED",
}

export default LoadingSteps;
