enum LoadingSteps {
  DOTNET_ADDED = "DOTNET_ADDED",
  MONACO_SERVICES_INSTALLED = "MONACO_SERVICES_INSTALLED",
  LANGUAGE_CLIENT_STARTED = "LANGUAGE_CLIENT_STARTED",
  LANGUAGE_SERVER_INITIALIZED = "LANGUAGE_SERVER_INITIALIZED",
}

export default LoadingSteps;
