export enum Channel {
  GET_WORKSPACE_PATH = "GET_WORKSPACE_PATH",
  READ_FILE = "READ_FILE",
  GET_EXAMPLES_PATH = "GET_EXAMPLES_PATH",
  GET_EXAMPLE_PROJECT = "GET_EXAMPLE_PROJECT",
  GET_WEBSOCKET_PORT = "GET_WEBSOCKET_PORT",
  START_LANGUAGE_SERVER = "START_LANGUAGE_SERVER",
}
