export enum Channel {
  GET_WORKSPACE_PATH = "GET_WORKSPACE_PATH",
  READ_FILE = "READ_FILE",
  GET_EXAMPLES_PATH = "GET_EXAMPLES_PATH",
  GET_EXAMPLE_PROJECT = "GET_EXAMPLE_PROJECT",
  START_LANGUAGE_SERVER = "START_LANGUAGE_SERVER",
  DOTNET_NOT_FOUND = "DOTNET_NOT_FOUND",
  GET_EXAMPLE_PROJECTS = "GET_EXAMPLE_PROJECTS",
  OPEN_PROJECT = "OPEN_PROJECT",
  GET_USER_PROJECTS = "GET_USER_PROJECTS",
  GET_USER_PROJECT = "GET_USER_PROJECT",
  GET_CONFIG_IN_PROJECT = "GET_CONFIG_IN_PROJECT",
  CREATE_DEFAULT_CONFIG = "CREATE_DEFAULT_CONFIG",
}
