enum SimObjects {
  AGENT = "AGENT",
  LAYER = "LAYER",
  BASIC_LAYER = "BASIC_LAYER",
  DEPENDENT_LAYER = "DEPENDENT_LAYER",
  RASTER_LAYER = "RASTER_LAYER",
  VECTOR_LAYER = "VECTOR_LAYER",
  ENTITY = "ENTITY",
}

export default SimObjects;
